language: python
sudo: required
dist: trusty
python:
- '3.5'
install:
- sudo apt-get update
- sudo apt-get -y install python3-pyqt5
- pip install -e .
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- make lint
- make test
