language: python
python:
- '2.7'
install:
- pip install -e .
- pip install -r requirements-dev.txt
script:
- make lint
- make test
- make
deploy:
  provider: releases
  api_key:
    secure: j7n6EsxGlNKbHTB/EeK0SO1kRJkhS9V7uvVMf2/+BjZcgb9imT/r4Vk2oRQpy914MuTEevzNK/XUqgxyAJlufD7EqsKK1Mt1nVnIfooHpfatZTWqhwJP2nZ2R4IT/ZR2y4XVMD0iyQxIwM/Jy4VkfRO+QixXtW07zpu12K/rh37FRIl56nk1wf7hOJ2xOwOMaWDC5YaEAS7bVvsyNfuFrHPraRbs42zuViSEoQAEW1+DhyOAe57K/g2SvY9frdMx2Wkc3VfB+96pqHf1YQGNsKytOAHwaajXXlP+Xhxxbu6o5L07oGrViB8yqeH/IKuHCBUDzabF2qu9sOwEB3LGL1U5Xdn7Yh3tWr9fJD6SD2sAmKhziAb19lZwO3ccCmsJYGgbYwf7K3mIWkqQAwQbwiF2Luel4TkhM/oJTD6mQKeSw2kCYVXmFVHRJ3pScF6rOZ/DCvz5Zja48ePllm35wyUbsOYTgypADh5joq6AQ8PPLOKzqhRTG3453BR1dWkFDDjpL6LjrBKgtsUyJBoDRVWH3iOnu+yUwkJzZGsoe6OvSYeMAy/M6c9iqFxRSOiTw31xwwa1PLFP1YVBuUWQpaStw4dFpyNF1/7z+YK3501vZUeRpXUmbcbI9FHHJ3Be3S2CLAa8MF5fAMTH8yEk36q2EG/Stx7gYCtu0urfGQE=
  file: dist/StenoDictate.app
  on:
    repo: arxanas/StenoDictate
    branch: travis-ci
