language: python
sudo: required
dist: trusty
python:
- '2.7'
install:
- pip install -e .
- pip install -r requirements-dev.txt
- sudo apt-add-repository -y ppa:benoit.pierre/plover
- sudo apt-get install -y python-dev pyqt5-dev-tools python-pyqt5 python-setuptools-pyqt
script:
- make lint
- make test
- make
