version: '{build}'
environment:
  matrix:
    - PYTHON: "C:\\Python35"

build:
  verbosity: minimal

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

test_script:
  - python -m pytest
  - python -m flake8 stenodictate
  - python -m flake8 --ignore D test
